apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - srv: infrastructure
        path: definitions/infrastructure/
      - srv: services
        path: definitions/services/
      - srv: outbox
        path: definitions/outbox/
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: app-component
              operator: In
              values:
                - infrastructure
        - matchExpressions:
            - key: app-component
              operator: In
              values:
                - services
        - matchExpressions:
            - key: app-component
              operator: In
              values:
                - outbox
  template:
    metadata:
      name: '{{srv}}'
      labels:
        app-component: '{{srv}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/tomas-rojo/argocd-test.git'
        targetRevision: main
        path: '{{path}}'
      destination:
        name: in-cluster
        namespace: app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
        syncOptions:
          - CreateNamespace=true