apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: infrastructure
        path: infrastructure
      - name: services
        path: services
      - name: outbox
        path: services
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: metadata.name
              operator: In
              values: ["platform-infrastructure"]
        - matchExpressions:
            - key: metadata.name
              operator: In
              values: ["platform-services"]
        - matchExpressions:
            - key: metadata.name
              operator: In
              values: ["platform-outbox"]
  template:
    metadata:
      name: 'platform-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/tomas-rojo/argocd-test.git
        targetRevision: main
        path: 'definitions/{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true