apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: infrastructure
        path: infrastructure
      - name: services
        path: services
      - name: outbox
        path: outbox
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: component
              operator: In
              values:
                - infrastructure"
        - matchExpressions:
            - key: component
              operator: In
              values: ["services"]
        - matchExpressions:
            - key: component
              operator: In
              values: ["outbox"]
  template:
    metadata:
      name: 'platform-{{.name}}'
      labels:
        component: '{{.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/tomas-rojo/argocd-test.git
        targetRevision: main
        path: 'definitions/{{.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true