apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: outbox
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default

  source:
    repoURL: https://github.com/tomas-rojo/argocd-test.git
    targetRevision: main
    path: services

  destination:
    name: in-cluster
    namespace: app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true